### ISSUE TITLE
Body fields is missing

### ISSUE THREAD

**Issue by kjetilhartveit** [jsaari97/netlify-ts#13]
Hello! It seems the body field is missing from my types. I haven't managed to track down the cause (don't have time now), but definitely happening in the `transformType()` function. 

This `console.log()` could help in tracking down the cause.

```node
if (widget.name === "body") {
    console.log('body types', types);
    // outputs: body types [ [ 'title: string;', 'date: string;' ], [] ]
    return types;
}
```

My config and have I've tried:

Config.yml
```yml
...
collections:
    - label: "Blog"
      name: "blog"
      folder: "content/post"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - {
                label: "Publish date",
                name: "publishDate",
                widget: "datetime",
                required: true,
            }
          - {
                label: "Featured Image",
                name: "thumbnail",
                widget: "image",
                required: false,
            }
          - { label: "Body", name: "body", widget: "markdown", required: true }
          - {
                label: "Created date",
                name: "createdDate",
                widget: "datetime",
                required: true,
            }
...
```

Generated type:
```typescript
export interface Blog {
  title: string;
  publishDate: string;
  thumbnail?: string;
  createdDate: string;
}
```
