### ISSUE TITLE
feature request: possibility for datetime widgets to be typed as Date

### ISSUE THREAD

**Issue by kjetilhartveit** [jsaari97/netlify-ts#15]
When generating fields with the widget `datetime` I'd like them to be typed as Date because gray-matter automatically parses these fields to Date.

Example Netlify config.yml:
```yml
collections:
    - label: "Blog"
      name: "blog"
      fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - {
                label: "Published date",
                name: "publishedDate",
                widget: "datetime",
                required: true,
            }
```

Generated types:
```typescript
export interface Blog {
  title: string;
  publishedDate: string;
}
```

Desired generated type:
```typescript
export interface Blog {
  title: string;
  publishedDate: Date;
}
```

My setup:
```
    "gray-matter": "^4.0.3",
    "netlify-ts": "^2.0.0",
```
